### ISSUE TITLE
Версионность кода

### ISSUE THREAD

**Issue by vintury** [SkanerSoft/J2ds#10]
Сейчас код активно развивается, в связи с чем достаточно часто появляются проблемы которые отсутствовали в определенном релизе, и чтобы понять есть ли проблема сейчас или просто используемая версия изменилась и несоответсвует документации, стоит более четко вести версионность кода. Именно требуется в каждом комите указывать новую минорную версию.
Помимо этого предлагаю ввести объект который сможет показывать версию игрового движка, к примеру эту информацию можно будет выводить следующей командой:

``` javascript
console.log(j2ds.version);
```

**Comment by SkanerSoft** [comment]
Сейчас да, иногда версии выходят по несколько раз в день, работа ведется активно. С версией пока решено не усложнять ситуацию, так как движок пока в разработке, и данная альфа версия не планируется выходить в массы в том виде, в котором она есть сейчас. Однако версия движка и прочая информация хранится в объекте j2ds.getInfo(), но он пока недоступен. Опять же - вводится поддержка геймпадов, из-за чего большАя часть работы проводится в режиме отладочных коммитов. В скором времени конечно исправится.

**Comment by likerRr** [comment]
> Именно требуется в каждом комите указывать новую минорную версию.

Версии нужно указывать в соответствии с вносимыми изменениями, а не постоянно новую. К тому же, в ходе разработки ПО, следуя концепции семантического версионирования, минорную версию следует увеличивать с каждым новым релизом (а не коммитом).

Но в целом я поддерживаю предложение. Версионность вести нужно на любом этапе разработки, пусть это и альфа.
