### ISSUE TITLE
[Bug] Полноэкраный режим

### ISSUE THREAD

**Issue by devinterx** [SkanerSoft/J2ds#17]
Полностью нерабочий метод, единственное что он делает - пытается изменить стиль(скалирует изображение), а должен вместо этого: 
- изменить размер канваса на всех слоях,
- изменить размер всех слоев.
- перед тем как изменять он должен сохранять свойства слоев(такие как заливка) и восстановить их когда размер изменен.
- IO пытается считать позицию мыши относительно сцены, а не рабочего слоя, естественно она остается ограниченной границами сцены, т.к. она не менялась - она хранит исходное состояние. 

Одним словом печалька, и пока что этот метод придется запретить.

**Comment by SkanerSoft** [comment]
Это устаревший метод, однако IO при включении полноэкранного режима обрабатывается корректно, как и, соответственно, слои. Для проверки просто вы можете открыть пример из папки Demo под названием fpsManager и после scene.init() дописать 

```
j2ds.getLayers().add('qwe', -1).fill('#E5E5E5');
scene.fullScreen(true);
```

Вы увидете, что позиция курсора так рассчитывается верно и задний слой так же отмасштабировался под весь экран.

Размеры всех имеющихся канвасов-слоев методом fullScreen() масштабируются, но не изменяют свой фактический размер. По этому поводу есть даже соответствующее видео:
https://www.youtube.com/watch?v=Jj_kS_ZUn4g

**Comment by devinterx** [comment]
..IO пытается считать позицию мыши относительно сцены.. - ты не совсем правильно понял, это не список текущих багов, Это список в чем проблема или может оказаться при рефакторинге.

Объясню этот пункт немножко подробней:
Предположим мы сделаем метод fullScreen, который будет делать layout.resize(w, h) для, всех слоев, но тогда, вот и сломается этот метод, т.к. размер сцены останется прежним, а координаты мы будем снимать в его пределах.

А так, да, для скалирования оно работает правильно, но мне не нужен scene.scaleToFullscreen() :sarcazm:

**Comment by devinterx** [comment]
И да,если метод устарел, помечай его через JSDoc как 
/**
...
     \* @deprecated
...
**/

**Comment by SkanerSoft** [comment]
Мысль уловил! К след. версии постараюсь поправить.

**Comment by devinterx** [comment]
я даже думаю, что правильнее бы было реализовать не только layout.resize но и scene.resize метод, а из фулскрина, дергать именно его, это добавит гибкости, для реализации переключения ланшафтного и портретного режимов

**Comment by SkanerSoft** [comment]
Добавил несколько функций сразу, продокументировал, в субботу обновлю, отлаживать надо, но в целом работает. Есть воможность менять размеры сцены, как фактические так и внутреигровые, скаллировать сцену (со слоями).

**Comment by devinterx** [comment]
коммит 501b89, добавил метод, но он работает с багами, в особенности страности происходят со статичными слоями, теми что не перерисовываются в цикле, так же теряется заливка.

Так что вопрос пока остается окрытым.

**Comment by devinterx** [comment]
Пофиксил в своем плагине ошибки коммита 501b89, серьезно для чего нужно было использовать временный канвас? и реализация двух методов resize() для scene и layout значительно сократила общий код. Так же добавил requestFullscreen, теперь это действительно фуллскрин, а не фуллпейдж. 

@SkanerSoft посмотри по возможности, все же такой вариант, будет более правильный, хоть у тебя и другие взгляды на архитектуру библиотеки.

P.S. т.к. в моем плагине нет еще документации, посмотреть результат CTRL+F11

**Comment by devinterx** [comment]
закрываю, как невостребованное.
