### ISSUE TITLE
Лицензия распространения

### ISSUE THREAD

**Issue by likerRr** [SkanerSoft/J2ds#2]
Было бы хорошо добавить информацию о лицензии распространения фреймворка

**Comment by SkanerSoft** [comment]
[Есть ведь](https://github.com/SkanerSoft/J2ds/wiki/J2ds---%D0%B8%D0%B3%D1%80%D0%BE%D0%B2%D0%BE%D0%B9-HTML5-%D0%B4%D0%B2%D0%B8%D0%B6%D0%BE%D0%BA)

**Comment by likerRr** [comment]
Спасибо. Может, вынести ее в корень проекта, как советует [github](https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository)?

**Comment by ivlev** [comment]
Может стоит пометить в соотвествии с принятой практикой? Чтобы вопросов не было. https://ru.wikipedia.org/wiki/Свободная_лицензия
