### ISSUE TITLE
функция isIntersect()

### ISSUE THREAD

**Issue by devweb99** [SkanerSoft/J2ds#24]
Нужно сделать возможность передавать туда массив. Для множественного отслеживания пересечений.

**Comment by devweb99** [comment]
а когда выйдет 0.6.4 ?

**Comment by devinterx** [comment]
Ну я поставил на первое число следующего месяца, но ты можешь не волноваться, правки уже доступны в development ветке, https://github.com/SkanerSoft/j2Ds/tree/development папочка dist содержит сейчас пример с массивами, как ты попросил + я закрыл [старющий баг](https://github.com/SkanerSoft/j2Ds/issues/8) когда боксы повернуты. Смотри, тестируй пробуй, как по тестируеш отпишись.

**Comment by devweb99** [comment]
спасибо

**Comment by devweb99** [comment]
Пишу вот так и у меня char не рисуется. 

 if (char.isIntersect(box)) {
     console.log(1);
  }   
  
  char.draw(7);

**Comment by devweb99** [comment]
все работает как надо. Спасибо.   Я тогда просто не то скачал.
