### ISSUE TITLE
Карта

### ISSUE THREAD

**Issue by devweb99** [SkanerSoft/J2ds#25]
Сделайте пожалуйста возможность рисовать карту вот таким вот образом
есть 2 массива 
1) сама карта
2) столкновения
выглядят массивы вот таким образом

var map = [[1,1,1],
                  [1,0,1]];

и второй массив точно так же только с collision .  где 1=false  0=true

**Comment by devweb99** [comment]
со слоями. Если добавить еще один массив то будет как дополнительный слой и можно было бы настраивать на заднем плане или же на переднем

**Comment by SkanerSoft** [comment]
А что мешает по такому массиву в нужных местах расставить BaseNode объекты? Они все равно невидимы, у них даже метода draw() нет, а вот проверить с ними столкновения очень даже можно.

**Comment by devweb99** [comment]
для откладки они должны быть видимы.  Да и потом я это все сделал. Хотел бы это увидеть в библиотеке. Я все это сделал только вот не получается оптимизировать так что бы можно было загружать несколько карт. А потом одной строчкой менять сцены. На данный момент у меня друг друга перезаписывают. То есть последняя созданная сцена будет рисоваться. Я даже менял названия объекта и все ровно.

**Comment by SkanerSoft** [comment]
для отладки у BaseNode есть drawBox() - который отобразит видимые их границы.

**Comment by devweb99** [comment]
Спасибо за совет. Заменил на baseNode. Я вставлял tails  вместо него.
Посмотрите пожалуйста код. Не получается сделать так что бы с начало подгрузить уровни а потом setGameState  загружать их при необходимости. 
локация - objects/map/location1.js    (допустим создал еще один уровень новым файлом "location2.js" Там от рисовал только локацию и необходимые параметры указал)

**Comment by devweb99** [comment]
Я адаптировал код. В любом случии спасибо вам за все.

**Comment by devinterx** [comment]
Закрываю, как не востребованное.
