### ISSUE TITLE
Непонятен раздел "Вывод изображения"

### ISSUE THREAD

**Issue by vintury** [SkanerSoft/J2ds#3]
Не смог разобраться как воспользоваться добавлением изображения, в документации описано в пункте "Вывод изображения", но там лишь указаны параметры которые передаются а как указать файл с изображением непонятно.

**Comment by SkanerSoft** [comment]
Чтобы спрайт-карта была успешно создана и доступна для движка, она должна полностью загрузиться. По этой причине, чтобы загружать спрайт-карту необходимо создать элемент IMG в DOM вашего документа:

```
<img alt="" src="my_folder/my_image.png" id="myImageFromFile" />
```

И затем в нужном месте игрового приложения:

```
var imageMap = scene.createImageMap('myImageFromFile');
```

Этой командой изображение исчезнет из видимой части DOM, но станет доступным для обработки внутри движка.

**Comment by SkanerSoft** [comment]
Upd: var imageMap = scene.createImageMap('my_folder/my_image.png');

**Comment by vintury** [comment]
Делаю вот так:

``` javascript
    var imageMap = scene.createImageMap('box_r.jpg');
    var pos = vec2df(10, 10),  // Позиция
        size = vec2df(50, 50), // Размер изображения
        frame = 1;             // Нужный кадр анимации
    scene.draw(pos, size, frame, imageMap);
```

Получаю ошибку:
`Uncaught TypeError: scene.draw is not a function`

Что я делаю не так?
Использую последнюю версию движка.

**Comment by SkanerSoft** [comment]
```
var imageMap = scene.createImageMap('box_r.jpg');

var sourceX = 0,    // Позиция первого кадра по X
sourceY = 0,    // Позиция первого кадра по Y
sourceH = 50,   // Высота первого кадра
sourceW = 50;   // Ширина первого кадра
frameCount = 1; // Количеество кадров, если это анимация

// Создание анимации
var anim = imageMap.createAnimation(sourceX, sourceY, sourceW, sourceH, frameCount);

var pos = vec2df(10, 10),  // Позиция
    size = vec2df(50, 50), // Размер изображения
    frame = 1;             // Нужный кадр анимации
scene.drawImage(pos, size, anim, frame);
```

**Comment by vintury** [comment]
Мне кажется для подобного функционала код достаточно сложный, не думал упростить схему?
Я думаю для простоты можно было бы использовать вот так:

``` javascript
var imageMap = scene.createImageMap('box_r.jpg');
scene.drawImage(pos, size, imageMap);
```

А если необходимо использовать анимацию то вот так:

``` javascript
var imageMap = scene.createImageMap('box_r.jpg');
var anim = imageMap.createAnimation(sourceX, sourceY, sourceW, sourceH, frameCount)
scene.drawImage(pos, size, anim, frame);
```

Мне видится неразумным каждый раз указывать параметры анимации даже если таковая не требуется...

**Comment by SkanerSoft** [comment]
Движок подразумевает, что в imageMap хранятся все изображения.
Пример: ![j2Ds Demo](http://spritedatabase.net/files/mobile/1356/Sprite/PS-OfficerNiao.png)
