### ISSUE TITLE
Нет информации по инициализации канваса

### ISSUE THREAD

**Issue by vintury** [SkanerSoft/J2ds#6]
В документации в разделе:  Минимальный игровой код
Написано:
"Холст (canvas) для отрисовки"
Но в самом приведенном коде данный параметр нигде не указан, пробовал инициализировать как в одном из уроков "scene.init('idCanvas', "#dddddd");" не получилось.

И в целом ниче что я баги на документацию завожу? Может это как-то иначе стоит делать?

**Comment by SkanerSoft** [comment]
Спасибо! Инициализация сцены согласно актуальной версии: 
    scene.init(640, 480);
Сам канвас создавать не трубуется.

Документацию подкорректировал.

**Comment by SkanerSoft** [comment]
Как вариант - можно писать все вопросы на форум: http://skanersoft.ru/forum/3

**Comment by vintury** [comment]
> Сам канвас создавать не трубуется.
> Мне кажется это неудобно, очень сложно управляться с HTML кодом в котором объекты генерируются отдельно. Существует ли альтернативный способ в котором явно указывается id канваса который необходимо использовать?

И как сейчас залить сцену цветом? Пробовал команду scene.fill("#dddddd"); результат не изменился.

На форуме другая беда, не могу найти кнопку зарегестрироваться: http://prntscr.com/8it703

**Comment by SkanerSoft** [comment]
Можно просто перейти на главную страницу сайта и зарегистрироваться.

Для заливки:
После инициализации сцены (после команды scene.init)

можно написать:

```
j2ds.layers.add('background', -1);
j2ds.layers.layer('background').fill('#dddddd');
```

**Comment by SkanerSoft** [comment]
Если используется команда scene.clear() - заливка самой сцены на будет видна. Если хочется заливать именно сцену - то scene.fill нужно использовать вместо scene.clear

**Comment by vintury** [comment]
Спасибо за помощь!
