### ISSUE TITLE
Размещение канваса в HTML коде

### ISSUE THREAD

**Issue by vintury** [SkanerSoft/J2ds#7]
Если создать канвас командой scene.init(500,500); то данный канвас в HTML коде размещается поверх существующих объектов, или наоборот снизу.
Примеры:
http://prntscr.com/8itw8a
http://prntscr.com/8itwch
На первом скрине показан канвас который описан в самом HTML коде, на втором показан канвас который в этомже коде создан инициадизацией сцены.

Мне кажется стоит сделать вариант возможности указывать id существующего канваса + оставить вариант с самосоздаваемым, но доработать его следующим образом: добавить к нему id чтобы была возможность подключить к CSS стиль индивидуально. Т.е. если на сцене будет несколько канвасов трудности с их расположением могут возникнуть.
В противном случае придется в каждой HTML создавать фреймы.

**Comment by SkanerSoft** [comment]
Основная канвас сцены имеет id 'sceneNode'.

**Comment by SkanerSoft** [comment]
По поводу других да, пофиксим.

**Comment by vintury** [comment]
Сейчас создаваемый  канвас не имеет id, см. скрин: http://prntscr.com/8j3m9u

**Comment by SkanerSoft** [comment]
Да, вижу. Исправим!
