### ISSUE TITLE
При повороте объекта его collision box не меняется

### ISSUE THREAD

**Issue by vintury** [SkanerSoft/J2ds#8]
При вращении объекта его Collision-box не меняется, ниже пример:

``` javascript
var cell = scene.addSpriteNode(vec2df(0, 0), 
                           vec2df(30, 30), 
                           scene.createImageMap('box_r.jpg').createAnimation(0, 0, 30, 30, 1));
cell.setPosition(input.getPosition());
cell.turn(45);
cell.draw();
cell.drawBox();
```

Скриншот результата:
http://prntscr.com/8k97hk

**Comment by SkanerSoft** [comment]
addSpriteNode не нужно делать в цикле. Иначе вы в цикле каждый раз грузите картинку из файла. Пощадите процессор... в цикле вы можете Обрабатывать объекты, создавать их нужно за его пределами.

По поводу collision-box понял, разбираемся.

**Comment by vintury** [comment]
Ох, точно, спасибо!
Кстати ваш форум не работает...

**Comment by SkanerSoft** [comment]
С ним тоже разбираемся, почему-то сервер, где он расположен перестал отвечать. Ответа от техподдержки пока нет. Если не починится, будем менять хостинг.

**Comment by devinterx** [comment]
Пофиксил баг, кому нужно проверяйте.

**Comment by devinterx** [comment]
Нужно пофиксить InputManager.onNode()

**Comment by devinterx** [comment]
Новый метод учитывает только пересечение, нужно еще учитывать, когда один узел находится в другом!

**Comment by devinterx** [comment]
Все ранее замеченные баги пофикшены
